In [98]:
import pandas as pd
import numpy as np

In [99]:
train1 = pd.read_csv('data/LP2_Telco-churn-second-2000.csv')

In [100]:
train1.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  5600-PDUJF    Male              0      No         No       6          Yes   
1  8292-TYSPY    Male              0      No         No      19          Yes   
2  0567-XRHCU  Female              0     Yes        Yes      69           No   
3  1867-BDVFH    Male              0     Yes        Yes      11          Yes   
4  2067-QYTCF  Female              0     Yes         No      64          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0                No             DSL             No  ...               No   
1                No             DSL             No  ...              Yes   
2  No phone service             DSL            Yes  ...              Yes   
3               Yes     Fiber optic             No  ...               No   
4               Yes     Fiber optic             No  ...              Yes   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0         Yes          No              No  Month-to-month              Yes   
1         Yes          No              No  Month-to-month              Yes   
2          No          No             Yes        Two year              Yes   
3          No          No              No  Month-to-month              Yes   
4         Yes         Yes             Yes  Month-to-month              Yes   

             PaymentMethod MonthlyCharges  TotalCharges Churn  
0  Credit card (automatic)          49.50         312.7    No  
1  Credit card (automatic)          55.00        1046.5   Yes  
2  Credit card (automatic)          43.95        2960.1    No  
3         Electronic check          74.35         834.2   Yes  
4         Electronic check         111.15        6953.4    No  

[5 rows x 21 columns]

In [101]:
train1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2043 entries, 0 to 2042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        2043 non-null   object 
 1   gender            2043 non-null   object 
 2   SeniorCitizen     2043 non-null   int64  
 3   Partner           2043 non-null   object 
 4   Dependents        2043 non-null   object 
 5   tenure            2043 non-null   int64  
 6   PhoneService      2043 non-null   object 
 7   MultipleLines     2043 non-null   object 
 8   InternetService   2043 non-null   object 
 9   OnlineSecurity    2043 non-null   object 
 10  OnlineBackup      2043 non-null   object 
 11  DeviceProtection  2043 non-null   object 
 12  TechSupport       2043 non-null   object 
 13  StreamingTV       2043 non-null   object 
 14  StreamingMovies   2043 non-null   object 
 15  Contract          2043 non-null   object 
 16  PaperlessBilling  2043 non-null   object 


In [102]:
train1.describe()

SeniorCitizen       tenure  MonthlyCharges
count    2043.000000  2043.000000     2043.000000
mean        0.168380    32.649046       64.712555
std         0.374295    24.376248       29.970010
min         0.000000     0.000000       18.550000
25%         0.000000     9.000000       35.825000
50%         0.000000    30.000000       70.250000
75%         0.000000    55.000000       89.625000
max         1.000000    72.000000      118.350000

In [103]:
train1.duplicated().sum()

0

In [104]:
train2 = pd.read_csv('data/Telco_churn_first_3000.csv')

In [105]:
train2.head()

customerID  gender  SeniorCitizen  Partner  Dependents  tenure  \
0  7590-VHVEG  Female          False     True       False       1   
1  5575-GNVDE    Male          False    False       False      34   
2  3668-QPYBK    Male          False    False       False       2   
3  7795-CFOCW    Male          False    False       False      45   
4  9237-HQITU  Female          False    False       False       2   

   PhoneService MultipleLines InternetService OnlineSecurity  ...  \
0         False           NaN             DSL          False  ...   
1          True         False             DSL           True  ...   
2          True         False             DSL           True  ...   
3         False           NaN             DSL           True  ...   
4          True         False     Fiber optic          False  ...   

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0            False       False       False           False  Month-to-month   
1             True       False       False           False        One year   
2            False       False       False           False  Month-to-month   
3             True        True       False           False        One year   
4            False       False       False           False  Month-to-month   

  PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
0             True           Electronic check      29.850000     29.850000   
1            False               Mailed check      56.950001   1889.500000   
2             True               Mailed check      53.849998    108.150002   
3            False  Bank transfer (automatic)      42.299999   1840.750000   
4             True           Electronic check      70.699997    151.649994   

   Churn  
0  False  
1  False  
2   True  
3  False  
4   True  

[5 rows x 21 columns]

In [106]:
train2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        3000 non-null   object 
 1   gender            3000 non-null   object 
 2   SeniorCitizen     3000 non-null   bool   
 3   Partner           3000 non-null   bool   
 4   Dependents        3000 non-null   bool   
 5   tenure            3000 non-null   int64  
 6   PhoneService      3000 non-null   bool   
 7   MultipleLines     2731 non-null   object 
 8   InternetService   3000 non-null   object 
 9   OnlineSecurity    2349 non-null   object 
 10  OnlineBackup      2349 non-null   object 
 11  DeviceProtection  2349 non-null   object 
 12  TechSupport       2349 non-null   object 
 13  StreamingTV       2349 non-null   object 
 14  StreamingMovies   2349 non-null   object 
 15  Contract          3000 non-null   object 
 16  PaperlessBilling  3000 non-null   bool   


In [107]:
train1["SeniorCitizen"].unique()

array([0, 1], dtype=int64)

In [108]:
train2["SeniorCitizen"].unique()

array([False,  True])

In [109]:
#mapping SeniorCitizen from 0,1 to False,True
train1["SeniorCitizen"] = train1["SeniorCitizen"].map({0: False, 1: True})

In [110]:
train1["SeniorCitizen"].unique()

array([False,  True])

In [111]:
train1["Partner"].unique()

array(['No', 'Yes'], dtype=object)

In [112]:
train1["Partner"] = train1["Partner"].map({"Yes": True, "No": False})

In [113]:
train1["Partner"].unique()

array([False,  True])

In [114]:
train1["Dependents"].unique()

array(['No', 'Yes'], dtype=object)

In [115]:
train1["Dependents"] = train1["Dependents"].map({"Yes": True, "No": False})
train1["Dependents"].unique()

array([False,  True])

In [116]:
train1["PaperlessBilling"].unique()

array(['Yes', 'No'], dtype=object)

In [117]:
#mapping PaperlessBilling from Yes,No to True,False
train1["PaperlessBilling"] = train1["PaperlessBilling"].map({"Yes": True, "No": False})
train1["PaperlessBilling"].unique()

array([ True, False])

In [118]:
#mapping PhoneService from Yes,No to True,False
train1["PhoneService"] = train1["PhoneService"].map({"Yes": True, "No": False})
train1["PhoneService"].unique()

array([ True, False])

In [119]:
train1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2043 entries, 0 to 2042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        2043 non-null   object 
 1   gender            2043 non-null   object 
 2   SeniorCitizen     2043 non-null   bool   
 3   Partner           2043 non-null   bool   
 4   Dependents        2043 non-null   bool   
 5   tenure            2043 non-null   int64  
 6   PhoneService      2043 non-null   bool   
 7   MultipleLines     2043 non-null   object 
 8   InternetService   2043 non-null   object 
 9   OnlineSecurity    2043 non-null   object 
 10  OnlineBackup      2043 non-null   object 
 11  DeviceProtection  2043 non-null   object 
 12  TechSupport       2043 non-null   object 
 13  StreamingTV       2043 non-null   object 
 14  StreamingMovies   2043 non-null   object 
 15  Contract          2043 non-null   object 
 16  PaperlessBilling  2043 non-null   bool   


In [120]:
train1["MultipleLines"].unique()

array(['No', 'No phone service', 'Yes'], dtype=object)

In [121]:
train2["MultipleLines"].unique()

array([nan, False, True], dtype=object)

In [122]:
train1["MultipleLines"] = train1["MultipleLines"].map({"Yes": True, "No": False, "No phone service": False})
train1["MultipleLines"].unique()

array([False,  True])

In [123]:
train2.isna().sum()

customerID            0
gender                0
SeniorCitizen         0
Partner               0
Dependents            0
tenure                0
PhoneService          0
MultipleLines       269
InternetService       0
OnlineSecurity      651
OnlineBackup        651
DeviceProtection    651
TechSupport         651
StreamingTV         651
StreamingMovies     651
Contract              0
PaperlessBilling      0
PaymentMethod         0
MonthlyCharges        0
TotalCharges          5
Churn                 1
dtype: int64

In [124]:
def check_unique_values(df, column):
    unique_values = df[column].unique()
    print(f"Unique values in {column}: {unique_values}")

In [125]:
check_unique_values(train1, "InternetService")

Unique values in InternetService: ['DSL' 'Fiber optic' 'No']


In [126]:
check_unique_values(train1, "OnlineSecurity")

Unique values in OnlineSecurity: ['No' 'Yes' 'No internet service']


In [127]:
check_unique_values(train1, "OnlineBackup")

Unique values in OnlineBackup: ['No' 'Yes' 'No internet service']


In [128]:
check_unique_values(train1, "DeviceProtection")

Unique values in DeviceProtection: ['No' 'Yes' 'No internet service']


In [129]:
check_unique_values(train1, "TechSupport")

Unique values in TechSupport: ['Yes' 'No' 'No internet service']


In [130]:
check_unique_values(train1, "StreamingTV")

Unique values in StreamingTV: ['No' 'Yes' 'No internet service']


In [131]:
check_unique_values(train1, "StreamingMovies")

Unique values in StreamingMovies: ['No' 'Yes' 'No internet service']


In [132]:
#function to map service columns to True,False
def map_service_columns(df, column):
    df[column] = df[column].map({
        "Yes": True,
        "No": False,
        "No internet service": False
    })
    return df

In [133]:
map_service_columns(train1, "OnlineSecurity")
map_service_columns(train1, "OnlineBackup")
map_service_columns(train1, "DeviceProtection")
map_service_columns(train1, "TechSupport")
map_service_columns(train1, "StreamingTV")
map_service_columns(train1, "StreamingMovies")

customerID  gender  SeniorCitizen  Partner  Dependents  tenure  \
0     5600-PDUJF    Male          False    False       False       6   
1     8292-TYSPY    Male          False    False       False      19   
2     0567-XRHCU  Female          False     True        True      69   
3     1867-BDVFH    Male          False     True        True      11   
4     2067-QYTCF  Female          False     True       False      64   
...          ...     ...            ...      ...         ...     ...   
2038  6840-RESVB    Male          False     True        True      24   
2039  2234-XADUH  Female          False     True        True      72   
2040  4801-JZAZL  Female          False     True        True      11   
2041  8361-LTMKD    Male           True     True       False       4   
2042  3186-AJIEK    Male          False    False       False      66   

      PhoneService  MultipleLines InternetService  OnlineSecurity  ...  \
0             True          False             DSL           False  ...   
1             True          False             DSL           False  ...   
2            False          False             DSL            True  ...   
3             True           True     Fiber optic           False  ...   
4             True           True     Fiber optic           False  ...   
...            ...            ...             ...             ...  ...   
2038          True           True             DSL            True  ...   
2039          True           True     Fiber optic           False  ...   
2040         False          False             DSL            True  ...   
2041          True           True     Fiber optic           False  ...   
2042          True          False     Fiber optic            True  ...   

      DeviceProtection  TechSupport  StreamingTV  StreamingMovies  \
0                False         True        False            False   
1                 True         True        False            False   
2                 True        False        False             True   
3                False        False        False            False   
4                 True         True         True             True   
...                ...          ...          ...              ...   
2038              True         True         True             True   
2039              True        False         True             True   
2040             False        False        False            False   
2041             False        False        False            False   
2042              True         True         True             True   

            Contract PaperlessBilling              PaymentMethod  \
0     Month-to-month             True    Credit card (automatic)   
1     Month-to-month             True    Credit card (automatic)   
2           Two year             True    Credit card (automatic)   
3     Month-to-month             True           Electronic check   
4     Month-to-month             True           Electronic check   
...              ...              ...                        ...   
2038        One year             True               Mailed check   
2039        One year             True    Credit card (automatic)   
2040  Month-to-month             True           Electronic check   
2041  Month-to-month             True               Mailed check   
2042        Two year             True  Bank transfer (automatic)   

     MonthlyCharges  TotalCharges Churn  
0             49.50         312.7    No  
1             55.00        1046.5   Yes  
2             43.95        2960.1    No  
3             74.35         834.2   Yes  
4            111.15        6953.4    No  
...             ...           ...   ...  
2038          84.80        1990.5    No  
2039         103.20        7362.9    No  
2040          29.60        346.45    No  
2041          74.40         306.6   Yes  
2042         105.65        6844.5    No  

[2043 rows x 21 columns]

In [134]:
train1["StreamingMovies"].unique()

array([False,  True])

In [135]:
train1["Churn"].unique()

array(['No', 'Yes'], dtype=object)

In [136]:
#mapping Churn from Yes,No to True,False
train1["Churn"] = train1["Churn"].map({"Yes": True, "No": False})
train1["Churn"].unique()

array([False,  True])

In [137]:
train1.head()

customerID  gender  SeniorCitizen  Partner  Dependents  tenure  \
0  5600-PDUJF    Male          False    False       False       6   
1  8292-TYSPY    Male          False    False       False      19   
2  0567-XRHCU  Female          False     True        True      69   
3  1867-BDVFH    Male          False     True        True      11   
4  2067-QYTCF  Female          False     True       False      64   

   PhoneService  MultipleLines InternetService  OnlineSecurity  ...  \
0          True          False             DSL           False  ...   
1          True          False             DSL           False  ...   
2         False          False             DSL            True  ...   
3          True           True     Fiber optic           False  ...   
4          True           True     Fiber optic           False  ...   

   DeviceProtection  TechSupport  StreamingTV  StreamingMovies  \
0             False         True        False            False   
1              True         True        False            False   
2              True        False        False             True   
3             False        False        False            False   
4              True         True         True             True   

         Contract PaperlessBilling            PaymentMethod MonthlyCharges  \
0  Month-to-month             True  Credit card (automatic)          49.50   
1  Month-to-month             True  Credit card (automatic)          55.00   
2        Two year             True  Credit card (automatic)          43.95   
3  Month-to-month             True         Electronic check          74.35   
4  Month-to-month             True         Electronic check         111.15   

   TotalCharges  Churn  
0         312.7  False  
1        1046.5   True  
2        2960.1  False  
3         834.2   True  
4        6953.4  False  

[5 rows x 21 columns]

In [ ]:
#checking if the columns of both dataframes are the same
train1.columns == train2.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [143]:
#checking the datatypes of the columns in train1
train1.dtypes

customerID           object
gender               object
SeniorCitizen          bool
Partner                bool
Dependents             bool
tenure                int64
PhoneService           bool
MultipleLines          bool
InternetService      object
OnlineSecurity         bool
OnlineBackup           bool
DeviceProtection       bool
TechSupport            bool
StreamingTV            bool
StreamingMovies        bool
Contract             object
PaperlessBilling       bool
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                  bool
dtype: object

In [144]:
train2.dtypes

customerID           object
gender               object
SeniorCitizen          bool
Partner                bool
Dependents             bool
tenure                int64
PhoneService           bool
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling       bool
PaymentMethod        object
MonthlyCharges      float64
TotalCharges        float64
Churn                object
dtype: object

In [148]:
train2.isna().sum()

customerID            0
gender                0
SeniorCitizen         0
Partner               0
Dependents            0
tenure                0
PhoneService          0
MultipleLines       269
InternetService       0
OnlineSecurity      651
OnlineBackup        651
DeviceProtection    651
TechSupport         651
StreamingTV         651
StreamingMovies     651
Contract              0
PaperlessBilling      0
PaymentMethod         0
MonthlyCharges        0
TotalCharges          5
Churn                 1
dtype: int64

In [ ]:
#merging both dataframes
train = pd.concat([train1, train2], ignore_index=True)

In [150]:
train.head()

customerID  gender  SeniorCitizen  Partner  Dependents  tenure  \
0  5600-PDUJF    Male          False    False       False       6   
1  8292-TYSPY    Male          False    False       False      19   
2  0567-XRHCU  Female          False     True        True      69   
3  1867-BDVFH    Male          False     True        True      11   
4  2067-QYTCF  Female          False     True       False      64   

   PhoneService MultipleLines InternetService OnlineSecurity  ...  \
0          True         False             DSL          False  ...   
1          True         False             DSL          False  ...   
2         False         False             DSL           True  ...   
3          True          True     Fiber optic          False  ...   
4          True          True     Fiber optic          False  ...   

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0            False        True       False           False  Month-to-month   
1             True        True       False           False  Month-to-month   
2             True       False       False            True        Two year   
3            False       False       False           False  Month-to-month   
4             True        True        True            True  Month-to-month   

  PaperlessBilling            PaymentMethod MonthlyCharges  TotalCharges  \
0             True  Credit card (automatic)          49.50         312.7   
1             True  Credit card (automatic)          55.00        1046.5   
2             True  Credit card (automatic)          43.95        2960.1   
3             True         Electronic check          74.35         834.2   
4             True         Electronic check         111.15        6953.4   

   Churn  
0  False  
1   True  
2  False  
3   True  
4  False  

[5 rows x 21 columns]

In [151]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        5043 non-null   object 
 1   gender            5043 non-null   object 
 2   SeniorCitizen     5043 non-null   bool   
 3   Partner           5043 non-null   bool   
 4   Dependents        5043 non-null   bool   
 5   tenure            5043 non-null   int64  
 6   PhoneService      5043 non-null   bool   
 7   MultipleLines     4774 non-null   object 
 8   InternetService   5043 non-null   object 
 9   OnlineSecurity    4392 non-null   object 
 10  OnlineBackup      4392 non-null   object 
 11  DeviceProtection  4392 non-null   object 
 12  TechSupport       4392 non-null   object 
 13  StreamingTV       4392 non-null   object 
 14  StreamingMovies   4392 non-null   object 
 15  Contract          5043 non-null   object 
 16  PaperlessBilling  5043 non-null   bool   


In [152]:
#saving the merged dataframe to a csv file
train.to_csv('data/Telco_churn_merged.csv', index=False)

In [153]:
test = pd.read_csv('data/Telco-churn-last-2000.csv')

In [154]:
test.head()

customerID gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7613-LLQFO   Male              0      No         No      12          Yes   
1  4568-TTZRT   Male              0      No         No       9          Yes   
2  9513-DXHDA   Male              0      No         No      27          Yes   
3  2640-PMGFL   Male              0      No        Yes      27          Yes   
4  3801-HMYNL   Male              0     Yes        Yes       1          Yes   

  MultipleLines InternetService       OnlineSecurity         OnlineBackup  \
0           Yes     Fiber optic                   No                   No   
1            No              No  No internet service  No internet service   
2            No             DSL                  Yes                   No   
3           Yes     Fiber optic                   No                   No   
4            No     Fiber optic                   No                   No   

      DeviceProtection          TechSupport          StreamingTV  \
0                   No                   No                  Yes   
1  No internet service  No internet service  No internet service   
2                  Yes                  Yes                  Yes   
3                   No                  Yes                   No   
4                   No                   No                  Yes   

       StreamingMovies        Contract PaperlessBilling     PaymentMethod  \
0                   No  Month-to-month              Yes  Electronic check   
1  No internet service  Month-to-month               No      Mailed check   
2                  Yes        One year               No  Electronic check   
3                   No  Month-to-month              Yes  Electronic check   
4                  Yes  Month-to-month               No      Mailed check   

   MonthlyCharges TotalCharges  
0           84.45      1059.55  
1           20.40        181.8  
2           81.70      2212.55  
3           79.50      2180.55  
4           89.15        89.15

In [155]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        2000 non-null   object 
 1   gender            2000 non-null   object 
 2   SeniorCitizen     2000 non-null   int64  
 3   Partner           2000 non-null   object 
 4   Dependents        2000 non-null   object 
 5   tenure            2000 non-null   int64  
 6   PhoneService      2000 non-null   object 
 7   MultipleLines     2000 non-null   object 
 8   InternetService   2000 non-null   object 
 9   OnlineSecurity    2000 non-null   object 
 10  OnlineBackup      2000 non-null   object 
 11  DeviceProtection  2000 non-null   object 
 12  TechSupport       2000 non-null   object 
 13  StreamingTV       2000 non-null   object 
 14  StreamingMovies   2000 non-null   object 
 15  Contract          2000 non-null   object 
 16  PaperlessBilling  2000 non-null   object 


In [156]:
map_service_columns(test, "OnlineSecurity")
map_service_columns(test, "OnlineBackup")
map_service_columns(test, "DeviceProtection")
map_service_columns(test, "TechSupport")
map_service_columns(test, "StreamingTV")
map_service_columns(test, "StreamingMovies")


customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7613-LLQFO    Male              0      No         No      12   
1     4568-TTZRT    Male              0      No         No       9   
2     9513-DXHDA    Male              0      No         No      27   
3     2640-PMGFL    Male              0      No        Yes      27   
4     3801-HMYNL    Male              0     Yes        Yes       1   
...          ...     ...            ...     ...        ...     ...   
1995  7912-SYRQT  Female              0      No         No       7   
1996  3557-HTYWR  Female              0      No         No      47   
1997  4816-JBHOV    Male              1      No         No       2   
1998  8920-NAVAY    Male              1      No         No      62   
1999  1699-TLDLZ  Female              0     Yes        Yes      16   

     PhoneService MultipleLines InternetService  OnlineSecurity  OnlineBackup  \
0             Yes           Yes     Fiber optic           False         False   
1             Yes            No              No           False         False   
2             Yes            No             DSL            True         False   
3             Yes           Yes     Fiber optic           False         False   
4             Yes            No     Fiber optic           False         False   
...           ...           ...             ...             ...           ...   
1995          Yes           Yes     Fiber optic           False         False   
1996          Yes           Yes             DSL            True          True   
1997          Yes            No             DSL           False         False   
1998          Yes           Yes     Fiber optic           False          True   
1999          Yes            No              No           False         False   

      DeviceProtection  TechSupport  StreamingTV  StreamingMovies  \
0                False        False         True            False   
1                False        False        False            False   
2                 True         True         True             True   
3                False         True        False            False   
4                False        False         True             True   
...                ...          ...          ...              ...   
1995             False        False        False            False   
1996             False         True        False             True   
1997             False        False        False            False   
1998              True         True         True             True   
1999             False        False        False            False   

            Contract PaperlessBilling              PaymentMethod  \
0     Month-to-month              Yes           Electronic check   
1     Month-to-month               No               Mailed check   
2           One year               No           Electronic check   
3     Month-to-month              Yes           Electronic check   
4     Month-to-month               No               Mailed check   
...              ...              ...                        ...   
1995  Month-to-month              Yes  Bank transfer (automatic)   
1996        Two year               No               Mailed check   
1997  Month-to-month              Yes           Electronic check   
1998        One year              Yes  Bank transfer (automatic)   
1999        Two year               No               Mailed check   

      MonthlyCharges TotalCharges  
0              84.45      1059.55  
1              20.40        181.8  
2              81.70      2212.55  
3              79.50      2180.55  
4              89.15        89.15  
...              ...          ...  
1995           75.10       552.95  
1996           74.05       3496.3  
1997           44.70         93.7  
1998          110.75      7053.35  
1999           19.70       301.55  

[2000 rows x 20 columns]

In [158]:
#mapping Churn from Yes,No to True,False
def map_columns(df, column):
    df[column] = df[column].map({
        "Yes": True,
        "No": False,
    })
    return df

In [159]:
map_columns(test, "Partner")
map_columns(test, "Dependents")
map_columns(test, "PaperlessBilling")
map_columns(test, "PhoneService")

customerID  gender  SeniorCitizen  Partner  Dependents  tenure  \
0     7613-LLQFO    Male              0    False       False      12   
1     4568-TTZRT    Male              0    False       False       9   
2     9513-DXHDA    Male              0    False       False      27   
3     2640-PMGFL    Male              0    False        True      27   
4     3801-HMYNL    Male              0     True        True       1   
...          ...     ...            ...      ...         ...     ...   
1995  7912-SYRQT  Female              0    False       False       7   
1996  3557-HTYWR  Female              0    False       False      47   
1997  4816-JBHOV    Male              1    False       False       2   
1998  8920-NAVAY    Male              1    False       False      62   
1999  1699-TLDLZ  Female              0     True        True      16   

      PhoneService MultipleLines InternetService  OnlineSecurity  \
0             True           Yes     Fiber optic           False   
1             True            No              No           False   
2             True            No             DSL            True   
3             True           Yes     Fiber optic           False   
4             True            No     Fiber optic           False   
...            ...           ...             ...             ...   
1995          True           Yes     Fiber optic           False   
1996          True           Yes             DSL            True   
1997          True            No             DSL           False   
1998          True           Yes     Fiber optic           False   
1999          True            No              No           False   

      OnlineBackup  DeviceProtection  TechSupport  StreamingTV  \
0            False             False        False         True   
1            False             False        False        False   
2            False              True         True         True   
3            False             False         True        False   
4            False             False        False         True   
...            ...               ...          ...          ...   
1995         False             False        False        False   
1996          True             False         True        False   
1997         False             False        False        False   
1998          True              True         True         True   
1999         False             False        False        False   

      StreamingMovies        Contract  PaperlessBilling  \
0               False  Month-to-month              True   
1               False  Month-to-month             False   
2                True        One year             False   
3               False  Month-to-month              True   
4                True  Month-to-month             False   
...               ...             ...               ...   
1995            False  Month-to-month              True   
1996             True        Two year             False   
1997            False  Month-to-month              True   
1998             True        One year              True   
1999            False        Two year             False   

                  PaymentMethod  MonthlyCharges TotalCharges  
0              Electronic check           84.45      1059.55  
1                  Mailed check           20.40        181.8  
2              Electronic check           81.70      2212.55  
3              Electronic check           79.50      2180.55  
4                  Mailed check           89.15        89.15  
...                         ...             ...          ...  
1995  Bank transfer (automatic)           75.10       552.95  
1996               Mailed check           74.05       3496.3  
1997           Electronic check           44.70         93.7  
1998  Bank transfer (automatic)          110.75      7053.35  
1999               Mailed check           19.70       301.55  

[2000 rows x 20 columns]

In [160]:
test["MultipleLines"] = test["MultipleLines"].map({
    "Yes": True,
    "No": False,
    "No phone service": False
})
test["MultipleLines"].unique()

array([ True, False])

In [161]:
test["SeniorCitizen"] = test["SeniorCitizen"].map({0: False, 1: True})
test["SeniorCitizen"].unique()

array([False,  True])

In [162]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        2000 non-null   object 
 1   gender            2000 non-null   object 
 2   SeniorCitizen     2000 non-null   bool   
 3   Partner           2000 non-null   bool   
 4   Dependents        2000 non-null   bool   
 5   tenure            2000 non-null   int64  
 6   PhoneService      2000 non-null   bool   
 7   MultipleLines     2000 non-null   bool   
 8   InternetService   2000 non-null   object 
 9   OnlineSecurity    2000 non-null   bool   
 10  OnlineBackup      2000 non-null   bool   
 11  DeviceProtection  2000 non-null   bool   
 12  TechSupport       2000 non-null   bool   
 13  StreamingTV       2000 non-null   bool   
 14  StreamingMovies   2000 non-null   bool   
 15  Contract          2000 non-null   object 
 16  PaperlessBilling  2000 non-null   bool   


In [163]:
#saveing the test dataframe to a csv file
test.to_csv('data/Telco_churn_test.csv', index=False)